version: '3.7'

services:
  currency-exchange:
    container_name: currency-exchange
    image: ivans23/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - db
    expose:
      - "8000"
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/currency_exchange?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      #SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/currency_exchange?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  currency-conversion:
    image: ivans23/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  api-gateway:
    image: ivans23/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 300m
    ports:
      - "9411:9411"
    expose:
      - "9411"
    networks:
      - currency-network

  db:
    container_name: db
    image: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "currency_exchange"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    networks:
      - currency-network


  naming-server:
    image: ivans23/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

volumes:
  db:

networks:
  currency-network: